apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
        - name: cont-1
          image: abhiram2404/bb:appimage
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: mysqldb

