apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bloodbank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db
  serviceName: "mysqldb"
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: cont-1
          image: abhiram2404/bb:dbimage
          ports:
            - containerPort: 3306

